server:
  port: 9000
server.tomcat.uri-encoding: UTF-8
eureka:
  client:
    healthcheck: true
    enabled: true
    service-url: 
      defaultZone: http://root:root@localhost:10000/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
#rabbitmq
#spring.rabbitmq.host: 192.168.210.130
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest
#spring:
#  rabbitmq:
#    publisher-confirms: true
#  application:
#    name: userAdmin
## REDIS (RedisProperties)
## Redis数据库索引（默认为0）
#spring.redis.database: 0  
## Redis服务器地址
#spring.redis.host: localhost
## Redis服务器连接端口
#spring.redis.port: 6379  
## Redis服务器连接密码（默认为空）
#spring.redis.password:  
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active: 8  
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait: -1  
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle: 8  
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle: 0  
## 连接超时时间（毫秒）
#spring.redis.timeout: 0
      

##########################  mysql   ##########################
spring.datasource.url: "jdbc:mysql://localhost:3306/chinotan?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
spring.datasource.username: root
spring.datasource.password: naruto5150126kid
spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"

logging.level.com.shyroke.mapper: debug


##########################  mybatis   ##########################
mybatis.mapper-locations: classpath:mybatis/*.xml

##########################  druid配置   ##########################
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource

# 初始化大小，最小，最大  
spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
# 配置获取连接等待超时的时间  
spring.datasource.maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  
spring.datasource.timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒  
spring.datasource.minEvictableIdleTimeMillis: 300000
# 校验SQL，Oracle配置 spring.datasource.validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用  
spring.datasource.validationQuery: SELECT 'x'
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小  
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
spring.datasource.filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据  
spring.datasource.useGlobalDataSourceStat: true

# 配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.chinotan.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非  空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false